### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by tmolteno** [CamberLoid/xr829#1]
This module is used on the Sipeed Lichee RV 86 Panel. I am building images for this (https://github.com/tmolteno/d1_build). Could you post some basic build instructions? Happy to help debug.

**Comment by CamberLoid** [comment]
Sorry for late response. Busy on university things these days.

I would like to say that the module is not ready yet, and there are still lots of modpost error/warning. Before I am available to do some further research and fix them you may need to manually fix them. A possible fix is attached below (Not commited).

Build method is something like https://github.com/tmolteno/d1_build/commit/a03aa5ee7137dee0663b1813e1974d1a81f81f0c , but i am not sure whether it will work.

Currently, under my Lichee RV Dock, ` make modules --directory=/usr/src/linux-headers-5.18.0-sun20i M=$(pwd) V=1 KBUILD_MODPOST_WARN=Y ` does work after applying the patch attached.

My expected approach is to provide this module as a dkms package, I managed to write a `dkms.conf` in my local environment but since it is not tested (and not available in my current Windows) i have not uploaded it yet.

```patch
diff --git a/umac/aes_ccm.c b/umac/aes_ccm.c
index bc19528..2efa1bc 100644
--- a/umac/aes_ccm.c
+++ b/umac/aes_ccm.c
@@ -19,6 +19,7 @@

 static void aes_ccm_prepare(struct crypto_cipher *tfm, u8 *scratch, u8 *a)
 {
+       MODULE_IMPORT_NS(CRYPTO_INTERNAL);
        int i;
        u8 *b_0, *aad, *b, *s_0;

@@ -54,6 +55,7 @@ void mac80211_aes_ccm_encrypt(struct crypto_cipher *tfm, u8 *scratch,
                               u8 *data, size_t data_len,
                               u8 *cdata, u8 *mic)
 {
+       MODULE_IMPORT_NS(CRYPTO_INTERNAL);
        int i, j, last_len, num_blocks;
        u8 *pos, *cpos, *b, *s_0, *e, *b_0;

@@ -93,6 +95,7 @@ void mac80211_aes_ccm_encrypt(struct crypto_cipher *tfm, u8 *scratch,
 int mac80211_aes_ccm_decrypt(struct crypto_cipher *tfm, u8 *scratch,
                              u8 *cdata, size_t data_len, u8 *mic, u8 *data)
 {
+       MODULE_IMPORT_NS(CRYPTO_INTERNAL);
        int i, j, last_len, num_blocks;
        u8 *pos, *cpos, *b, *s_0, *a, *b_0;

@@ -134,6 +137,7 @@ int mac80211_aes_ccm_decrypt(struct crypto_cipher *tfm, u8 *scratch,

 struct crypto_cipher *mac80211_aes_key_setup_encrypt(const u8 key[])
 {
+       MODULE_IMPORT_NS(CRYPTO_INTERNAL);
        struct crypto_cipher *tfm;

        tfm = crypto_alloc_cipher("aes", 0, CRYPTO_ALG_ASYNC);
diff --git a/umac/aes_cmac.c b/umac/aes_cmac.c
index b3afa28..9d87b43 100644
--- a/umac/aes_cmac.c
+++ b/umac/aes_cmac.c
@@ -38,6 +38,7 @@ static void gf_mulx(u8 *pad)
 static void aes_128_cmac_vector(struct crypto_cipher *tfm, size_t num_elem,
                                const u8 *addr[], const size_t *len, u8 *mac)
 {
+       MODULE_IMPORT_NS(CRYPTO_INTERNAL);
        u8 scratch[2 * AES_BLOCK_SIZE];
        u8 *cbc, *pad;
        const u8 *pos, *end;
@@ -116,6 +117,7 @@ void mac80211_aes_cmac(struct crypto_cipher *tfm, const u8 *aad,

 struct crypto_cipher *mac80211_aes_cmac_key_setup(const u8 key[])
 {
+       MODULE_IMPORT_NS(CRYPTO_INTERNAL);
        struct crypto_cipher *tfm;

        tfm = crypto_alloc_cipher("aes", 0, CRYPTO_ALG_ASYNC);
```

**Comment by samuk** [comment]
Do you think you'll return to this? Or is it abandoned?

**Comment by CamberLoid** [comment]
> Do you think you'll return to this? Or is it abandoned?

Sorry for late response. Were busy for my school-things, and my bachelor degree.
I have no plan to **abandon** this project but just **pause development** of this stalled project. 
I may notify you and re-open this issue when I return to this project. Closing the issue as not planned.
